export const READ = 'READ'
export const READ_SUCCESS = 'READ_SUCCESS'
export const CREATE = 'CREATE'
export const CREATE_SUCCESS = 'CREATE_SUCCESS'
export const DELETE = 'DELETE'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'
export const UPDATE = 'UPDATE'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const CREATE_ERROR = 'CREATE_ERROR'
export const READ_ERROR = 'READ_ERROR'
export const UPDATE_ERROR = 'UPDATE_ERROR'
export const DELETE_ERROR = 'DELETE_ERROR'

